### ISSUE TITLE
Make documentation more accessible

### ISSUE THREAD

**Issue by peteyy** [RisingStack/nx-observe#1]
It would be nice to make sure the documentation is usable by everyone:
- Words like "stack" or "call stack" are not known by everyone please include the documentation or include links to explanation about using them.
- Make sure the reader knows why they need the latest browser.
- Provide real life examples for documentation (function noop does not describe behavior)

**Comment by peteyy** [comment]
- in the readme only include core API provide further info on docs page (maybe hosted on github pages for free)

**Comment by peteyy** [comment]
- come up with a documentation format and stick with it (uppercase headings links etc.) there are great examples at GitHub explore projects with great wikis

**Comment by solkimicreb** [comment]
Thx, I plan to rewrite the docs to make more sense. I will use your advice (:
