### ISSUE TITLE
[question] No plan to support IE?

### ISSUE THREAD

**Issue by akhoury** [RisingStack/nx-observe#3]
it is a pain in the a$$, I know, but it is possible with a shim, even [ie8](https://github.com/ractivejs/ractive/issues/1451) :p

**Comment by solkimicreb** [comment]
It is not possible sadly.

The repo relies heavily on ES6 proxies, which can't be fully polyfilled. Adding hooks on dynamically added (expando) properties is something that is impossible without proxies.

The only chance of supporting IE is by them adding Proxy support, which I definitely won't happen ):

**Comment by akhoury** [comment]
> Adding hooks on dynamically added (expando) properties is something that is impossible without proxies.

true. Thanks
